export const PHOTOGRAPHERS = [
  {
    id: '1',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Zenith Studio',
    multiCity: false,
    hasVerified: false,
  },
  {
    id: '2',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Aakash Photography',
    multiCity: true,
    hasVerified: false,
  },
  {
    id: '1',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Zenith Studio',
    multiCity: false,
    hasVerified: false,
  },
  {
    id: '2',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Aakash Photography',
    companyLogo: 'https://www.gravatar.com/avatar/05dfd4b41340d09cae045235eb0893c3?d=mp',
    multiCity: true,
    hasVerified: false,
  },
  {
    id: '1',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Zenith Studio',
    multiCity: false,
    hasVerified: false,
  },
  {
    id: '2',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Aakash Photography',
    multiCity: true,
    hasVerified: true,
  },
  {
    id: '1',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Zenith Studio',
    companyLogo: 'https://primefaces.org/cdn/primeng/images/demo/avatar/amyelsner.png',
    multiCity: false,
    hasVerified: false,
  },
  {
    id: '2',
    firstName: 'Amol',
    lastName: 'Sontakke',
    email: 'Amol Sontakke',
    phoneNumber: '7972122384',
    companyName: 'Aakash Photography',
    multiCity: true,
    hasVerified: false,
  },
];
